services:
  social-net-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5454:5432"
    volumes:
      - pgSocialData:/var/lib/postgresql/data
volumes:
  pgSocialData: