services:

  api:
    env_file: .env.docker
    build: 
      dockerfile: Dockerfile
      context: ./
    ports:
      - "4444:4444"
    environment:
      APP_PORT: ${APP_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgSocialData:/var/lib/postgresql/data
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    volumes:
      - redisData:/data
volumes:
  pgSocialData:
  redisData: