services:
  redis:
    build: 
      dockerfile: Dockerfile.redis
      context: redis-like
    expose: ["4000"]
    networks: [ internal ]

  kv.dev:
    build: 
      dockerfile: Dockerfile.kv.dev
      context: kv-server
    ports: [ "8080:3000" ]
    environment:
      REDIS_URL: http://redis-like:4000
    depends_on: [ redis ]
    networks: [ internal ]
    volumes:
      - type: bind
        source: ./kv-server/app
        target: /src/app

networks:
  internal: